name: MF Maven Release

on:
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write
    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-release-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-release-
          ${{ runner.os }}-maven-

    - name: Perform release
      uses: maven-flow/release@main
      with:
        maven-args: '-Darguments="-DMAVEN_PKG_REPO_URL=${{ vars.MAVEN_PKG_REPO_URL }}"'
        push-changes: true

    # run build post-release to execute needed actions (such as merging to open PRs)
    - name: Run Build
      run: gh workflow run mf-maven-build.yml --ref ${{ github.ref_name }}
      env:
        GH_TOKEN: ${{ github.token }}
